linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true
  gocognit:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/cloudfoundry/bosh-cli
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  whitespace:
    multi-func: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - musttag
    - nakedret
    - noctx
    - nolintlint
    - reassign
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

  # enable later:
  # - stylecheck
  # - revive
  # - whitespace

  # don't enable:
  # - asciicheck
  # - deadcode    # deprecated, replaced by unused
  # - depguard    # if enabled, all imports beside Go std lib need to be explicitly allowed in .golangci.yaml (wtf!?)
  # - exhaustive
  # - gochecknoglobals
  # - gochecknoinits
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - lll
  # - nestif
  # - prealloc
  # - scopelint
  # - structcheck # deprecated, replaced by unused
  # - testpackage
  # - varcheck    # deprecated, replaced by unused
  # - wsl

issues:
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'unnamedResult: consider giving a name to these results'
    - '(Expect directory permissions to be 0750 or less|Expect (WriteFile|file) permissions to be 0600 or less)'

  exclude-rules:
    - path: api/v1alpha1
      linters:
        - goimports

    # Disable these linters for test files.
    - path: _test\.go
      linters:
        - dupl
        - gocritic
        - funlen
        - revive
        - musttag

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

    - linters:
        - revive
      text: "that stutters"

    - path: zz_.*\.go
      linters:
        - revive
      text: "it will be inferred from"

  include:
    - EXC0011 # disable excluding of issues about missing package comments from stylecheck

  # Show all errors for all linters. Setting these to 0 disables limiting error reporting.
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  skip-dirs:
    - test/
    - fakes/
  timeout: 15m
